from includes.vipsignal import vip_signal
from includes.affilate import Affiliate
from includes.keyboards import Keyboards
from includes.payment_method import paymentmethod
from includes.faq import faq
from includes.functions import Functions 
from includes.challnges import challnges
from includes.channel import channel
from includes.analytics import analytics
from includes.send_message import send_message
from includes.discount_coes import discount_code
from includes.admins import admins
from includes.about import about
from includes.type_of_payment import type_payment