from includes.modules import StatesGroup,State

class ChannelsEdit(StatesGroup):
    MESSAGE = State()
    CONFRIM = State()
    PHOTO = State()
    PHOTO_ADD = State()
    PHOTO_REMOVE = State()
    INLINE = State()
    INLINE_DES = State()
    INLINE_ADD = State()
class AddJoinChannel(StatesGroup):
    TITLE = State()
    CONFIRM = State()
class SettingsForm(StatesGroup):
    buttons = State()
    welcome_message = State()
class AddButtonForm(StatesGroup):
    title = State()
    description = State()
    photo = State()
    type = State()
    place = State()
    verb = State()
    verb_name = State()
# Additional states for WelcomeMessageForm
class WelcomeMessageForm(StatesGroup):
    view_welcome_message = State()
    change_message = State()
    confirm_edit = State()
class AddDicsountCode(StatesGroup):
    SURE = State()
    TITLE = State()
    DESCRAPTION = State()
    CHECK = State()
    SEND_PHOTO = State()
    CONIFRM = State()
class Affiliate_State(StatesGroup):
    CONFIRM = State()
class vip_signal_state(StatesGroup):
    SELECT = State()
    SELECT_PAYMENT = State()
    SELECT_DATE = State()
    SELECT_CONFIRM = State()
    PAYMENT_OR_BROKER = State()
    CONFIRM_SEND_NUMBER = State()
    CONFIRM_PAY = State()
    REJECT = State()
    ACCOUNT_BROKER = State()
    ACCOUNT_EXISTS = State()
    ACCOUNT_EXISTS_CONFIRM = State()
    ACCOUNT_CREATION_CONFIRM = State()
    ACCOUNT_CREATION_FULLNAME = State()
    ACCOUNT_CREATION_ADREEAS = State()
    ACCOUNT_CREATION_PHONENUMBER = State()
    ACCOUNT_CREATION_EMAIL = State()
    ACCOUNT_CREATION_IDCARD_FRONT = State()
    ACCOUNT_CREATION_IDCARD_BACK = State()
    ACCOUNT_CREATION_LICNESSCARD_FRONT = State()
    ACCOUNT_CREATION_LICNESSCARD_BACK = State()
    ACCOUNT_CREATION_SELECT_BROKER = State()
    ACCOUNT_CREATION_SELECT_PAYMENT = State()
    ACCOUNT_CREATION_CONFARMATION = State()
    ADD_PRICE_TO_VIP_SIGNAL_TITLE = State()
    ADD_PRICE_TO_VIP_SIGNAL_PRICE = State()

class payment_method_state(StatesGroup):
    SELECT = State()
    CONFIRM_CREATE =State()
    TITLE = State()
    DESCRAPTION = State()
    PHOTO = State()
    PHOTO_CONFIRM = State()
    CONFIRM = State()
    CONFIRM_DELETE =State()
class ButtonStates(StatesGroup):
    entering_message = State()
    entering_button_title = State()
    choosing_button_type = State()
    entering_url = State()
    entering_photo = State()
    entering_title_button = State()
    entering_callback_message = State()
    entering_msg_of_button = State()
class add_discount_code(StatesGroup):
    entering_text = State()
    entering_message = State()
    entering_photo = State()
    confirm = State()
    entering_button_title = State()
    choosing_button_type = State()
    entering_msg_of_button = State()
    entering_title = State()

class AdminsStates(StatesGroup):
    CHANGE_ROLE = State()
    ADD_NEW_ADMIN = State()
class PaymentStates(StatesGroup):
    entering_amount_days = State()
    entering_price = State()
    confirming = State()
    entering_done = State()